name: Build and deploy development

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  REGISTRY_URL: private.azurecr.io
  SERVICE_NAME: ugg-demo-service
  K8S_CLUSTER: ugg-k8s-dev
  RESOURCE_GROUP: ugg-development
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login into ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME_DEVELOPMENT }}
          password: ${{ secrets.REGISTRY_PASSWORD_DEVELOPMENT }}

      - name: Build and push docker containers
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY_URL }}/${{ env.SERVICE_NAME }}:latest
            ${{ env.REGISTRY_URL }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
            
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-kubectl@v3
        id: install_kubectl
        
      - name: Login to azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/aks-set-context@v3
        with:
           resource-group: ${{ env.RESOURCE_GROUP }}
           cluster-name: ${{ env.K8S_CLUSTER }}
           
      - name: Deploy service
        uses: Azure/k8s-deploy@v4
        with:
           resource-group: ${{ env.RESOURCE_GROUP }}
           name: ${{ env.K8S_CLUSTER }}
           action: deploy
           strategy: blue-green
           private-cluster: true
           manifests: |
              k8s/ugg-demo.yml
           images: |
              ${{ env.REGISTRY_URL }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
